### ISSUE TITLE
possibly all ConstInterfaces/their derived classes require refactoring

### ISSUE THREAD

**Issue by renemilk** [wwu-numerik/dune-stuff#38]
Pulling cv-qualified functions into derived classes that declare the same function with the using directive is illegal:

> 7.3.3 The using declaration [namespace.udecl]
> 
> 14/ If a function declaration in namespace scope or block scope has the same name and the same  parameter types as a function introduced by a using-declaration, and the declarations do not declare the same function, the program is ill-formed.

**Comment by renemilk** [comment]
And ofc there's a _special case_:

> 15/ When a using-declaration brings names from a base class into a derived class scope, member functions and member function templates in the derived class override and/or hide member functions and member function templates with the same name, parameter-type-list (8.3.5), cv-qualification, and ref-qualifier (if any) in a base class (rather than conflicting).

So basically AFAICT, in classes you can pull the exact same function definition with using, write it again in the class body and that overrides the using one w/o it being a standarad violation. IMO 14/ still says our usage is ill-formed though. We're not "using" functions with the same parameter_types, cv-quali and ref-quali.

**Comment by ftalbrecht** [comment]
WTF? I am not sure I get this. Are you (= the standard) saying there is no way to have two methods with the same name and different cv qualifiers in base and derived classes? E.g., the following is not valid:
```
struct A {
  void foo() const {}
}

struct B : public A {
  using A::foo;
  void foo() {}
}
```
?

**Comment by renemilk** [comment]
Yeah, that is my understanding of the two paragraphs.

**Comment by renemilk** [comment]
Ah, to clarify, you can _have_ them, you just cannot be _pulling_ one in with diff cv/ref-quali by "using" it

**Comment by ftalbrecht** [comment]
Wow, so I would have to do
```
struct B : public A {
  void foo() const {
    A::foo();
  }
  void foo() {
    // do something
  }
};
```
That would seem awfully inconvenient. 14/ however, does not say anything about cv qualifiers. The function in the derived class does have the same name and parameters, only the cv qualifier is different. So I am not sure if 14/ applies here. 15/ should not be a problem as we do not hide anything (since the cv qualifier differs). Could you find any external resources or discussions other than the standard on this one?

**Comment by renemilk** [comment]
In 14/ it is not necessary for the cv-quali to be the same for the program to become ill formed. That is why it is not mentioned. Imo what you should do is have a base class that's smart depending on whether it tpl arg is const or not.

**Comment by ftalbrecht** [comment]
Agreed. In the case of the grid providers it is not that trivial, however. We would need a helper traits like `is_grid_part` to decide via `std::enable_if` if the method should be const or not. This could be implemented in `dune/stuff/grid/layers.hh`. I am not sure if a correct implementation of `is_grid_part` is possible, though (since the `GridPart` base class does not publicly expose all types needed for such a check, if I remember correctly; thank you, dune-fem). If this is not possible we could implement such a switch in the existing traits in `layers.hh` (aka let the traits there not only expose `Type` but also `is_const` or the like). This would be far less elegant but would also solve the problem. We could then move all functionality from the const grid provider interface to the non-const one and drop the const implementation. I do not have the time atm to do this, however.

**Comment by renemilk** [comment]
Pretty sure you're overthinking this again, anyway. So if I find the time to solve this in a simpler fashion, super. Otherwise it'll just stay technically broken until it becomes a real problem for someone

**Comment by ftalbrecht** [comment]
In the case of grid providers: quite sure I am not. For grid views we can have a method
```
  GridViewType layer< ..., view >() const
  GridViewType layer< ..., view >()
```
while for grid parts we can only have 
```
  GridPartType layer< ..., part >()
```
where in all cases `Grid{Part,View}Type` is a non-const type. So in order to enable the const variant for grid views we would need to detect if something is a grid view, etc...

**Comment by renemilk** [comment]
Since you're apparently still thinking about it you're clearly overthinking it ;-)
You're also overlooking that I said depending on whether the tpl arg is const or not.

**Comment by ftalbrecht** [comment]
Mhm, considering this a bit further: The way everything is implemented right now does not really allow all of this. Problem is that the methods I mentioned above depend on
```c++
virtual GridType& grid() const = 0;
```
in the const interface variant and
```c++
virtual GridType& grid() = 0; 
```
in the other variant. Thus there is no template argument entering the interface of which you can detect the constness. This is, however, present in the default provider. We could thus merge the const interface, the non-const interface and the default provider. Thus every derived class would be required to instantiate the base interface by giving it a grid reference. We could then do all of the magic in the interface depending on the constness of the incoming argument, which is perhaps more in the spirit of what you had in mind. I agree, however, that further considerations should not be made without actually implementing it... :)

**Comment by renemilk** [comment]
Closing all remaining dune-stuff tickets. Please see https://github.com/dune-community and the dune-xt modules there.
